### ISSUE TITLE
USER STORY: Home Page

### ISSUE THREAD

**Issue by EdwardShanahan07** [EdwardShanahan07/fitness-meals#1]
As a **User**, I can **view the home page** so that **I can learn about the application**

**Acceptance Criteria**
- The home page should have a well-defined navigation
- The user can register or log in through the navigation
- The home page has an About section to give the user information about the site
- The home page features three of the most recently created recipes

**Tasks**

- [x] Create an index.html file
- [x] Create a navigation bar
- [x] Create an effective About section
- [x] Create functionality to render the three most recent recipes
- [x] Test the Home page
