### ISSUE TITLE
USER STORY: Comment 

### ISSUE THREAD

**Issue by EdwardShanahan07** [EdwardShanahan07/fitness-meals#10]
As a **User**, I can **comment on members' recipes** so that **I ask questions about the recipe**

**Acceptance Criteria**

- Users can comment on recipes on the recipe detail page
- Users must be login in order to comment 
- Users can view comments

**Tasks**

- [ ] Create a comment model
- [ ] Create the comment view functionality 
- [ ] Test by commenting on the recipe
