### ISSUE TITLE
USER STORY: Account Registration 

### ISSUE THREAD

**Issue by EdwardShanahan07** [EdwardShanahan07/fitness-meals#2]
As a **User**, I can **register an account** so that **I can create and share my recipes**

**Acceptance Criteria**
- The user will fill out the registration form
- The user will provide a username or email. 
- The user will create a password and confirm it matches 
- The user will get a message if they registered correctly

**Tasks**

- [ ] Install the Django AllAuth library 
- [ ] Configure the AllAuth library 
- [ ] Use Django message to display a successful or unsuccessful message
- [ ] Test functionality by creating an account
