### ISSUE TITLE
USER STORY: Login

### ISSUE THREAD

**Issue by EdwardShanahan07** [EdwardShanahan07/fitness-meals#3]
As a **User** I can **login** so that **I can use the application's full functionality**

**Acceptance Criteria**
- The user will enter a username or email and password to log in 
- The user will get a correct message if the credentials are incorrect 
- The user will get an error message if the credentials are incorrect

**Tasks**

- [ ] Style login.html 
- [ ] Create functionality for the login form
- [ ] Use Django message to display a successful or unsuccessful message
- [ ] Test functionality by logging in
