### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by EdwardShanahan07** [EdwardShanahan07/fitness-meals#4]
As a **user**, I can **log out** so that **I can keep my account secure**

**Acceptance Criteria**
- The user will click the sign-out button 
- The user will redirect to the logout page

**Tasks**

- [ ] Style logout.html
- [ ] Create functionality to sign out users
- [ ] Use Django message to display a successful message if the user logs out
- [ ] Test functionality by logging out
