### ISSUE TITLE
USER STORY: Delete Recipe

### ISSUE THREAD

**Issue by EdwardShanahan07** [EdwardShanahan07/fitness-meals#7]
As a **User**, I can **delete my recipes** so that **I can remove the recipe from the application**

**Acceptance Criteria**

- Users will have a delete button on their recipes
- The user will have to confirm if they want to delete a recipe
- The user will get a message if the recipe is deleted successfully 
- The user will be redirected to recipes page

**Tasks**

- [ ] Add delete_recipe.html
- [ ] Add delete_recipe class in views
- [ ] Test delete recipe functionality
