### ISSUE TITLE
USER STORY: View Recipes

### ISSUE THREAD

**Issue by EdwardShanahan07** [EdwardShanahan07/fitness-meals#8]
As a **User** I can **view recipes** so that **I can view members' recipes**

**Acceptance Criteria**
Users can see a complete list of user-shared recipes 

**Tasks**

- [ ] Create recipes.html file
- [ ] create recipes class view 
- [ ] Test functionality recipes.html
